routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/', 'EmployeeController@index')->name('index');
Route::get('/show/{id}', 'EmployeeController@show')->name('show');

app/Assignment.php
<?php

namespace Crewman;

use Illuminate\Database\Eloquent\Model;

class Assignment extends Model
{
    public function employer()
    {
        return $this->belongsTo('Crewman\Employer');
    }

    public function getPeriodAttribute()
    {
        $start_date_day = date('Y-m-d', strtotime($this->start_date));

        if (is_null($this->end_date)) {
            $period = sprintf('Since %s', $start_date_day);
        } else {
            $end_date_day = date('Y-m-d', strtotime($this->end_date));
            $period = $start_date_day == $end_date_day
                ? $start_date_day
                : sprintf('%s–%s', $start_date_day, $end_date_day);
        }

        return $period;
    }
}

app/Country.php
<?php

namespace Crewman;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    //
}

app/Employee.php
<?php

namespace Crewman;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Employee extends Model
{
    public function employments()
    {
        return $this->hasMany('Crewman\Employment');
    }

    public function roles()
    {
        return $this->hasMany('Crewman\Role');
    }

    public function leaves()
    {
        return $this->hasMany('Crewman\Leave');
    }

    public function getMostRecentEmployment()
    {
        $today = date('Y-m-d');

        return $this->employments()
            ->where('start_date', '<=', $today)  // no future employments
            ->orderBy('start_date', 'desc')
            ->first()
            ?? new Employment;
    }

    public function getMostRecentEmployer()
    {
        return $this->getMostRecentEmployment()->getMostRecentAssignment()->employer;
    }

    public function getRoleInAssignment($assignment_id)
    {
        return $this->roles->where('assignment_id', $assignment_id)->first() ?? new Role;
    }

    public function getLeavesInAssignment($assignment_id)
    {
        return $this->leaves->where('assignment_id', $assignment_id) ?? [];
    }

    public function getFullNameAttribute()
    {
        return sprintf('%s %s', $this->first_name, $this->last_name);
    }
}

app/Employer.php
<?php

namespace Crewman;

use Illuminate\Database\Eloquent\Model;

class Employer extends Model
{
    //
}

app/Employment.php
<?php

namespace Crewman;

use Illuminate\Database\Eloquent\Model;

class Employment extends Model
{
    public function assignments()
    {
        return $this->belongsToMany('Crewman\Assignment');
    }

    public function getMostRecentAssignment()
    {
        $now = date('Y-m-d H:i:s');

        return $this->assignments()
            ->where('start_date', '<=', $now)  // no future assignments
            ->orderBy('start_date', 'desc')
            ->first()
            ?? new Assignment;
    }

    public function isCurrent()
    {
        $now = date('Y-m-d');
        return $this->start_date <= $now && (is_null($this->end_date) || $this->end_date > $now);
    }

    public function isPast()
    {
        return $this->end_date <= date('Y-m-d');
    }

    public function isFuture()
    {
        return $this->start_date > date('Y-m-d');
    }
}

app/Leave.php
<?php

namespace Crewman;

use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{
    //
}

app/Role.php
<?php

namespace Crewman;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Role extends Model
{
    //
}

app/User.php
<?php

namespace Crewman;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace Crewman\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace Crewman\Http\Controllers;

use Crewman\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();

        return view('pages.index', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::find($id);

        return view('pages.show', ['employee' => $employee]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/includes/assignment_details.blade.php
<div class='d-table-row'>
    <span class='d-table-cell text-nowrap'>
        <strong>Start date:&nbsp;</strong>
    </span>
    <span class='d-table-cell'>
        {{ $assignment->start_date }}
    </span>
</div>

@if (!is_null($assignment->end_date))
    <div class='d-table-row'>
        <span class='d-table-cell'>
            <strong>End date: </strong>
        </span>
        <span class='d-table-cell'>
            {{ $assignment->end_date }}
        </span>
    </div>
@endif

@if (count($leaves) > 0)
    <div class='d-table-row'>
        <span class='d-table-cell'>
            <strong>Leave{{ count($leaves) > 1 ? 's' : '' }}: </strong>
        </span>
        <span class='d-table-cell align-top'>
            <ul>
                @foreach ($leaves as $leave)
                    <li>{{ $leave->start_date }}–{{ $leave->end_date }} ({{ $leave->reason }})</li>
                @endforeach
            </ul>
        </span>
    </div>
@endif

resources/views/includes/css.blade.php
<link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />

resources/views/includes/footer.blade.php
<footer>
    <div class="contact">
        <span>Martin Schrøder</span>
        <span><span class="fa">&#61443;</span>m.schroder@posteo.no</span>
        <span><span class="fa">&#61589;</span>+47 96 90 70 97</span>
    </div>

    <div class="copyright">
        © 2019 Martin Schrøder
    </div>
</footer>

resources/views/includes/js.blade.php
<script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/script.js') }}"></script>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
@include('includes.css')
@include('includes.js')
<title>@yield('title')</title>
</head>
<body>
    @include('includes.header')
    <main class="main">
        @yield('content')
    </main>
    @include('includes.footer')
</body>
</html>

resources/views/pages/index.blade.php
@extends('layouts.main')
@section('title', 'CREWMAN – Employee overview')
@section('content')
    <div class="container">
        <div class="row">
            <h1 class="mt-4">
                Employees
                <small>{{ count($employees) }} employees found</small>
            </h1>

            <div id="employees-display-selector" class="w-100 d-flex justify-content-end">
                <a class="{{ app('request')->input('display') != 'list' ? 'disabled' : '' }}" href="{{ route('index') }}" title="Display as grid" data-toggle="tooltip">
                    <span class="fa">&#61450;</span>
                </a>
                <a class="{{ app('request')->input('display') == 'list' ? 'disabled' : '' }}" href="{{ route('index', ['display' => 'list']) }}" title="Display as list" data-toggle="tooltip">
                    <span class="fa{{ app('request')->input('display') !== 'list' ? ' highlight_color' : '' }}">&#61497;</span>
                </a>
            </div>

            <div id="employees-grid" class="card-deck{{ app('request')->input('display') == 'list' ? ' d-none' : '' }}">
                @foreach ($employees as $employee)
                    <div class="card mb-4 clickable" data-href="{{ route('show', ['id' => $employee->id]) }}">
                        <div class="card-image-container">
                            <img class="card-img-top img-fluid" src="{{ asset('images/profile_pictures/' . $employee->id_number . '.jpg') }}" alt="Profile picture" />
                        </div>

                        <div class="card-body">
                            <h5 class="card-title">
                                {{ $employee->full_name }}
                            </h5>
                            <div class="card-text">
                                <p>
                                    <div><strong>ID number</strong></div>
                                    <div>{{ $employee->id_number }}</div>
                                </p>
                                <p>
                                    <div><strong>Employer</strong></div>
                                    <div>{{ $employee->getMostRecentEmployer()->name ?? '' }}</div>
                                </p>
                            </div>
                        </div>
                    </div>

                    @if ($loop->iteration % 2 == 0)
                        {{-- line break after 2 cards for sm --}}
                        <div class="w-100 d-none d-sm-block d-md-none"></div>
                    @endif
                    @if ($loop->iteration % 3 == 0)
                        {{-- line break after 3 cards for md --}}
                        <div class="w-100 d-none d-md-block d-lg-none"></div>
                    @endif
                    @if ($loop->iteration % 4 == 0)
                        {{-- line break after 4 cards for lg --}}
                        <div class="w-100 d-none d-lg-block d-xl-none"></div>
                    @endif
                    @if ($loop->iteration % 5 == 0)
                        {{-- line break after 5 cards for xl --}}
                        <div class="w-100 d-none d-xl-block"></div>
                    @endif
                @endforeach

                @for ($i = 0; $i < 4; $i++)
                    <div class="card" style="height: 0; border: 0;"></div>
                    @if ((count($employees) + $i + 1) % 2 == 0)
                        <div class="w-100 d-none d-sm-block d-md-none"></div>
                    @endif
                    @if ((count($employees) + $i + 1) % 3 == 0)
                        <div class="w-100 d-none d-md-block d-lg-none"></div>
                    @endif
                    @if ((count($employees) + $i + 1) % 4 == 0)
                        <div class="w-100 d-none d-lg-block d-xl-none"></div>
                    @endif
                    @if ((count($employees) + $i + 1) % 5 == 0)
                        <div class="w-100 d-none d-xl-block"></div>
                    @endif
                @endfor
            </div>

            <table id="employees-table" class="table table-striped table-hover{{ app('request')->input('display') != 'list' ? ' d-none' : '' }}">
                <thead>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>ID number</th>
                    <th>Most recent employer</th>
                </thead>

                <tbody>
                    @foreach ($employees as $employee)
                        <tr class="clickable" data-href="{{ route('show', ['id' => $employee->id, 'display' => 'list']) }}">
                            <td>{{ $employee->first_name }}</td>
                            <td>{{ $employee->last_name }}</td>
                            <td>{{ $employee->id_number }}</td>
                            <td>{{ $employee->getMostRecentEmployer()->name ?? '' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/pages/show.blade.php
@extends('layouts.main')
@section('title', 'CREWMAN – Employee details: ' . $employee->full_name)
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div id="abstract" class="sticky-top">
                    <div class="profile-picture">
                        <img src="{{ asset('images/profile_pictures/' . $employee->id_number . '.jpg') }}" alt="Profile picture" />
                    </div>

                    <div>
                        <strong>{{ $employee->full_name }}</strong>
                    </div>

                    <div>
                        <strong>ID number: </strong>{{ $employee->id_number }}
                    </div>

                    <div id="quick-actions" class="list-group">
                        @foreach ([
                            ['action' => null, 'text' => 'Messages', 'badge' => ['text' => '2', 'type' => 'info']],
                            ['action' => null, 'text' => 'Calendar', 'badge' => null],
                            ['action' => null, 'text' => 'Contract details', 'badge' => ['text' => 'Expiring', 'type' => 'danger']],
                        ] as $row)
                            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="{{ $row['action'] }}">
                                {{ $row['text'] }}
                                @if (!is_null($row['badge']))
                                    <span class="badge badge-pill badge-{{ $row['badge']['type'] }}">{{ $row['badge']['text'] }}</span>
                                @endif
                            </a>
                        @endforeach
                    </div>
                </div>
            </div>

            <div class="col-md-9">
                <nav class="sticky-top">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{{ route('index', app('request')->has('display') ? ['display' => app('request')->input('display')] : null) }}">
                                Employees
                            </a>
                        </li>
                        <li class="breadcrumb-item active">
                            {{ $employee->full_name }}
                        </li>
                    </ol>
                </nav>

                <div id="employments" class="accordion">
                    <h1>Employments</h1>

                    @foreach ($employee->employments->reverse() as $employment)
                        <div class="card">
                            <h2 class="clickable card-header" data-toggle="collapse" data-target="#employment-{{ $employment->id }}">
                                {{ $employment->name }}

                                <small>
                                    @isset($employment->end_date)
                                        <span class="text-nowrap">{{ $employment->start_date }}</span>–<span class="text-nowrap">{{ $employment->end_date }}</span>
                                    @elseif($employment->start_date <= date('Y-m-d'))
                                        since <span class="text-nowrap">{{ $employment->start_date }}</span>
                                    @else
                                        from <span class="text-nowrap">{{ $employment->start_date }}</span>
                                    @endif
                                </small>
                            </h2>

                            <div id="employment-{{ $employment->id }}" class="collapse{{ $employment->isCurrent() ? ' show' : '' }}" data-parent="#employments">
                                <div class="card-body">
                                    @if (count($employment->assignments) > 0)
                                        <h3>Assignments</h3>
                                        <table id="assignments" class="table table-striped table-hover">
                                            <thead>
                                                <th>Assignment</th>
                                                <th>Employer</th>
                                                <th>Role</th>
                                                <th>Period</th>
                                            </thead>

                                            <tbody>
                                                @foreach ($employment->assignments as $assignment)
                                                    @php ($role = $employee->getRoleInAssignment($assignment->id))
                                                    @php ($leaves = $employee->getLeavesInAssignment($assignment->id))

                                                    <tr data-toggle="popover" data-html="true" data-trigger="hover" title="Assignment details" data-content="@include('includes.assignment_details', ['assignment' => $assignment, 'leaves' => $leaves])">
                                                        <td>{{ $assignment->description }}</td>
                                                        <td>{{ $assignment->employer->name }}</td>
                                                        <td>
                                                            @if (!empty($role->id))
                                                                {{ $role->name }} <i>({{ ucfirst($role->type) }})</i>
                                                            @endisset
                                                        </td>
                                                        <td>
                                                            {!! preg_replace('/(\d{4}-\d{2}-\d{2})/', '<span class="text-nowrap">$1</span>', $assignment->period) !!}
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    @else
                                        No assignments
                                    @endif
                                </div>
                            </div>
                        </div>
                    @endforeach

                    @if (count($employee->employments) < 2)
                        <div class="card" />
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection